### ISSUE TITLE
in the Kleene-Post solution for 6.16, X and Y are undefined

### ISSUE THREAD

**Issue by xdavidliu** [lwins-lights/Introduction-to-the-Theory-of-Computation-Hints#3]
what are X and Y in that solution? It is never mentioned.

**Comment by lwins-lights** [comment]
The proof uses induction here. So X and Y are just arbitrary set \subseteq [m] (of course they should make sense the premise of A_{n-1} and B_{n-1} given above).

**Comment by xdavidliu** [comment]
thanks. Also, as an aside, I found your proof (but also the other 3-4 proofs of Kleene-Post I've found) extremely difficult to understand, especially the final few lines. In fact, I still don't really understand any of these proofs,  and I've been staring at these for pretty much the past 6 hours or so.

If you have a chance, please take a look at my [Stackexchange question](https://cs.stackexchange.com/q/131537/82288).

**Comment by lwins-lights** [comment]
@xdavidliu Well the notations are indeed a bit annoying. Having a second look I think the basic idea is just construct two languages A and B (seen as infinite binary strings) by working out each bit in order. For example, at some stage you work out that, temporarily (I'll slightly abuse notation here)
A = 00010101010???????????????...
B = 001010101010101???????????...
and for the first 5 Turing machine (all Turing machines can be well ordered), among them no one reduces A to B, or reduces B to A.
Then, what you should do next is basically fix some "?" to guarantee that for the 6th Turing machine, it does not reduce A to B or reduce B to A. And so on so forth.

**Comment by xdavidliu** [comment]
why in your example does A have 11 bits set, and B has 15 bits set, but you are talking about the 6th Turing machine? For diagonalization, shouldn't I be expecting all three to be approximately the same number, i.e. 5, 5, and 5, or do you have some sort of triply nested loop that is looping over some kind of cartesian product of (# set bits in A) x (# set bits in B) x (number of "first" TMs)?

**Comment by xdavidliu** [comment]
also, if you are proving by induction, what is the base case? Is it just A = ?????? B = ??????

**Comment by xdavidliu** [comment]
In the proof, what's the significance of the "m+1" string, and how do we know that it must either be in both the oracles with A and A' or in neither?

**Comment by xdavidliu** [comment]
I'm confused about one of the steps in the proof. You seem to "extend the prefix" m to m', and claim that if you extend it long enough, then eventually we'll find an m' for which **all** A' in the resulting family of infinite bitrings will have the oracle TM that calls A' with the same value of its m+1 bit as the oracle TM which calls the original A.

This claim is completely non-obvious to me; where does it come from?

**Comment by xdavidliu** [comment]
I wrote another version of this proof [and posted it as answer](https://cs.stackexchange.com/a/131570/82288). Comments welcome

**Comment by lwins-lights** [comment]
@xdavidliu Awesome! You are very welcome to merge it into the repo.
