### ISSUE TITLE
solution for 6.28b is wrong

### ISSUE THREAD

**Issue by xdavidliu** [lwins-lights/Introduction-to-the-Theory-of-Computation-Hints#4]
The current solution puts the constant 1 directly in the sentence, which is not allowed. 

The correct answer is phi(x) = "for any y, either y = 0 or y + 0 = x or there exists some z != 0 for which x + z = y."

This works because it's just saying that "any natural number is either 0, 1, or greater than 1".

For clarity we're using the sentence version of the constant 0 from part a instead of actually putting 0 directly into the sentence. When fully written out, it would look something like this:

phi(x) = "for any y either (for all k, y + k = k) or (there exists a z such that for all k, z + k = k and y + z = x) or (there exists a p for which for all k, p + k != k and x + p = y)"

**Comment by lwins-lights** [comment]
I have checked it again. You are correct: we should define "x=1" at first.
